#!/usr/bin/env bash

STATUS="$(playerctl status)"

get_status() {
	if [[ $STATUS == "Playing" ]]; then
		echo "images/icons/music/pause-button.png"
	else
		echo "images/icons/music/play-button.png"
	fi
}

if [[ "$1" == "--status" ]]; then
	get_status
fi
